### PR TITLE
Add leaf_edges option to disable edges to leaf nodes.

### PR DESCRIPTION
**Pull request by drewherron**
This is a Boolean option that turns off the final edge lines to a leaf node.

There's an example in the documentation of multi-line nodes, representing leaf nodes as strings and using a newline character. I'm calling svgling within a wrapper function that needs to take in trees as single, quoted strings. The newline character wasn't working in my case, so I made these changes. 

Tested on Debian (only).

### CODE REVIEW

**Comment by rawlins** [comment]
Thanks, I'll take a look!

Could you clarify further what wasn't working for you / do you have an example? Was this via nltk's parser?

**Comment by drewherron** [comment]
Yes, I'm using NLTK, here's the beginning of the relevant part of my program:

```
import svgling
from nltk.tree import Tree

def generate_syntax_tree_image(tree_structure, output_filepath='somepath/tree.svg'):
    tree = Tree.fromstring(tree_structure)
    tree_figure = svgling.draw_tree(tree, leaf_edges=False)
    ...etc

```    
And in my main file I'm importing that function, and reading in a JSON file where trees are stored as strings. But just for testing, I did make a main function in that tree image file:
```
if __name__ == '__main__':
    filepath = "test_tree.svg"
    test_tree_structure = "(CP (C' (C \u2205) (TP (DP (D' (D The) (NP (N' etc... " # (\u2205 == null)
    generate_syntax_tree_image(test_tree_structure, filepath)
 ```
This only ever worked for me when the entire tree was enclosed in quotes. For me it had to be double quotes because of the x-bar apostrophe, otherwise single quotes works. In either case, I can't add quotes for an internal string on the leaf nodes, and that would be the only way to get a newline \n to work. Even simple trees like:
`"(AdjP (Adj (Adj\nBig)))"` or `'(AdjP (Adj ("Adj\nBig")))'` 
didn't work. 

And now that I've spent more time on this today , I see it must be an issue with incorporating NLTK (and starting out with strings, which is why I went straight to`Tree.fromstring`). I can get the newline to work by cutting out NLTK entirely and using your example from the documentation. But then, to store that in JSON I think I'd have to store my trees like this:
```
"tree": "(\"TP\", (\"DP\", (\"D every"), (\"NP\", (\"N\", \"cat\"))), (\"TP\", \"1\", (\"TP\", (\"DP\", (\"D\", \"some\"), (\"NP\", (\"N\", \"dog\"))), (\"TP\", \"3\", (\"TP\", (\"DP\", \"t\", \"1\"), (\"VP\", (\"V\", \"likes\"), (\"DP\", \"t\", \"3\")))))))"
```
So, if there aren't any issues with my code, it may still be useful for people who are stuck with string trees. If all else works, one adjustment you/I may want to make is leaf distance from parent.

tree_example

**Comment by rawlins** [comment]
Quick followup: I'm planning on merging (a version of) this, because I think it's a reasonable FR for svgling itself. I'll probably make some tweaks: change how leaf nodes are identified, change the spacing (or make it configurable), and possibly generalize this to a new `EdgeStyle`. If you're interested in working on this further let me know and I can leave a review, though I don't mind starting from your PR myself either. I'll probably get to this next week.

In the interim (I had to reconstruct the details of how to do this), it may be useful to know that nltk actually does support newlines in nodes, just not easily. You have to change the named parameters `node_pattern` and `leaf_pattern`, and to do this properly (as far as I know) involves duplicating some tree internal [code](https://www.nltk.org/_modules/nltk/tree/tree.html#Tree). Here's a recipe, that works for me with svgling display:

```
import re
# dup internal nltk code
brackets = "()"
open_b, close_b = brackets
whitespace = r' \t\f\v' # this is what's different, nltk uses `\s`
open_pattern, close_pattern = (re.escape(open_b), re.escape(close_b))
node_pattern = rf"[^{whitespace}{open_pattern}{close_pattern}]+"
leaf_pattern = node_pattern

nltk.Tree.fromstring("(test tes\nt2)", leaf_pattern=leaf_pattern, node_pattern=node_pattern)
```

It's possible that other internal aspects of `nltk` won't handle such nodes gracefully, I'm not confident about this.

**Comment by rawlins** [comment]
Thanks again for the contribution, merged via 3834aeb819e9 and c9498d28704!

You can see that I changed the distance calculations a bit from your original implementation. If you want to recover the spacing you had in your examples, this will under most normal circumstances be doable by setting: `svgling.core.EmptyEdge.default_distance = 1.0`. (The default behavior is now to render leaf nodes exactly as if they were a second line.)

**Comment by drewherron** [comment]
Oh sorry I didn't respond, it's finals week...
I probably couldn't have helped much anyway, I'm really not that familiar with the codebase. But I see how you implemented (and improved) the change, it looks good. Thanks for the merge!

**Pull request closed without merging**
